#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/server: Launch the application and any extra required processes
#                locally.

# ensure everything in the app is up to date.
script/update
