#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

script/bootstrap
